---
- name: Remove build-essential if required
  apt:
    name: build-essential
    state: absent
  when:
    - psad_path.stat.exists == False
    - build_essential_check.stdout.find('no packages found') != -1
