---
# handlers file for ansible-psad
- name: restart psad
  service:
    name: psad
    state: restarted

- name: enable psad
  service:
    name: psad
    enabled: yes

- name: reload psad
  service:
    name: psad
    state: reloaded

- name: reload systemd
  command: systemctl daemon-reload
